// swift-tools-version:5.9
// This file is generated by build_spm_release.sh
// Do not edit by hand. Edit the template at
// templates/Package.swift.tmpl instead.
//
// Layout (20 binary targets total, surfaced as 5 library products):
//
//   Shared (byte-identical across all variants -- shipped once):
//     util_ios_Shared, wbxaecodec_Shared, wbxaudioengine_Shared, mediastores_ios_Shared
//     sqlite3_Shared, crypto_Shared, ssl_Shared, cjose_Shared, jansson_Shared,
//     CoreUtilities_Shared, SCFUtilities_Shared
//     (the last 7 were previously nested inside UCFBridge.framework/Frameworks;
//      they ship as siblings so Xcode/SPM can re-sign them for devices)
//
//   Variant-specific (WebexSDK + UCFBridge are recompiled per variant):
//     WebexSDK_Full,    UCFBridge_Full
//     WebexSDK_Meeting, UCFBridge_Meeting
//     WebexSDK_Wxc,     UCFBridge_Wxc
//     WebexSDK_Message, UCFBridge_Message
//
//   Broadcast (standalone, shipped once -- its own product):
//     WebexBroadcastExtensionKit
//
// Each WebexSDK* library product links the 11 shared targets plus the 2
// variant-specific targets for its flavour, so consumers still get
// `import WebexSDK` regardless of which library product they depend on.
//
// WebexBroadcastExtensionKit is a separate product (the SwiftPM equivalent of
// the WebexBroadcastExtensionKit CocoaPod). It only links system frameworks and
// communicates with the host app over a local socket, so it has no dependency
// on the WebexSDK frameworks. Add it to your Broadcast Upload Extension target,
// NOT to your main app target, and `import WebexBroadcastExtensionKit` there.
//
// The dedup is safe only as long as the 11 "Shared" frameworks remain
// byte-identical across all 4 variants. build_spm_release.sh verifies that
// invariant at packaging time and refuses to dedup on divergence. The
// broadcast framework is resolved as a single published copy and validated on
// its own, so it is not compared across the four variant folders.

import PackageDescription

let version = "3.17.0"
let base = "https://github.com/webex/webex-ios-sdk/releases/download/\(version)"

let package = Package(
    name: "WebexSDK",
    platforms: [.iOS(.v15)],
    products: [
        .library(
            name: "WebexSDK",
            targets: [
                "WebexSDK_Full",
                "UCFBridge_Full",
                "util_ios_Shared",
                "wbxaecodec_Shared",
                "wbxaudioengine_Shared",
                "mediastores_ios_Shared",
                "sqlite3_Shared",
                "crypto_Shared",
                "ssl_Shared",
                "cjose_Shared",
                "jansson_Shared",
                "CoreUtilities_Shared",
                "SCFUtilities_Shared",
            ]
        ),
        .library(
            name: "WebexSDKMeeting",
            targets: [
                "WebexSDK_Meeting",
                "UCFBridge_Meeting",
                "util_ios_Shared",
                "wbxaecodec_Shared",
                "wbxaudioengine_Shared",
                "mediastores_ios_Shared",
                "sqlite3_Shared",
                "crypto_Shared",
                "ssl_Shared",
                "cjose_Shared",
                "jansson_Shared",
                "CoreUtilities_Shared",
                "SCFUtilities_Shared",
            ]
        ),
        .library(
            name: "WebexSDKWxc",
            targets: [
                "WebexSDK_Wxc",
                "UCFBridge_Wxc",
                "util_ios_Shared",
                "wbxaecodec_Shared",
                "wbxaudioengine_Shared",
                "mediastores_ios_Shared",
                "sqlite3_Shared",
                "crypto_Shared",
                "ssl_Shared",
                "cjose_Shared",
                "jansson_Shared",
                "CoreUtilities_Shared",
                "SCFUtilities_Shared",
            ]
        ),
        .library(
            name: "WebexSDKMessage",
            targets: [
                "WebexSDK_Message",
                "UCFBridge_Message",
                "util_ios_Shared",
                "wbxaecodec_Shared",
                "wbxaudioengine_Shared",
                "mediastores_ios_Shared",
                "sqlite3_Shared",
                "crypto_Shared",
                "ssl_Shared",
                "cjose_Shared",
                "jansson_Shared",
                "CoreUtilities_Shared",
                "SCFUtilities_Shared",
            ]
        ),
        .library(
            name: "WebexBroadcastExtensionKit",
            targets: [
                "WebexBroadcastExtensionKit",
            ]
        ),
    ],
    targets: [
        // ---------- Shared (one copy, referenced by every variant library) ----------
        .binaryTarget(
            name: "util_ios_Shared",
            url: "\(base)/WebexSDK-Shared-util_ios.xcframework.zip",
            checksum: "8bd43701cc830bf8a9e4ea6db02920df85a21a5d47deb7ccfb29d89e4ff719fc"
        ),
        .binaryTarget(
            name: "wbxaecodec_Shared",
            url: "\(base)/WebexSDK-Shared-wbxaecodec.xcframework.zip",
            checksum: "1da6461d3aa1270bf4e2152255982ee00a0c642d9f32f3d5faf3e7a3384ba0e5"
        ),
        .binaryTarget(
            name: "wbxaudioengine_Shared",
            url: "\(base)/WebexSDK-Shared-wbxaudioengine.xcframework.zip",
            checksum: "baf396e0c328a0728cd1d0d78f2c0588b7adc7e72ede08266566395173700fc6"
        ),
        .binaryTarget(
            name: "mediastores_ios_Shared",
            url: "\(base)/WebexSDK-Shared-mediastores_ios.xcframework.zip",
            checksum: "8a595e394c906458a5dff83ff7246600fcdda272e98bbebcad44b0c349be660d"
        ),
        .binaryTarget(
            name: "sqlite3_Shared",
            url: "\(base)/WebexSDK-Shared-sqlite3.xcframework.zip",
            checksum: "2dd38e26c6b83161656d8480cf14db26f3342f2ffb1da3e4fdfa33a1b6855b96"
        ),
        .binaryTarget(
            name: "crypto_Shared",
            url: "\(base)/WebexSDK-Shared-crypto.xcframework.zip",
            checksum: "4b9dd8ce55988da2882ce13069c9e51858dfe4fa92867c2294c32811b15792a2"
        ),
        .binaryTarget(
            name: "ssl_Shared",
            url: "\(base)/WebexSDK-Shared-ssl.xcframework.zip",
            checksum: "7c8b1f9d3117103b708d2d39dde665589b4c888eaad8fa1924721749f632ad70"
        ),
        .binaryTarget(
            name: "cjose_Shared",
            url: "\(base)/WebexSDK-Shared-cjose.xcframework.zip",
            checksum: "3ce8f8afa5ff7f1e261826583e67a552cb2c85734d55506edbc3252d07f0bb3c"
        ),
        .binaryTarget(
            name: "jansson_Shared",
            url: "\(base)/WebexSDK-Shared-jansson.xcframework.zip",
            checksum: "6038c73a2749e208cf6f48dffd8277af9d9610c837fc204def99a79b6bfaeed5"
        ),
        .binaryTarget(
            name: "CoreUtilities_Shared",
            url: "\(base)/WebexSDK-Shared-CoreUtilities.xcframework.zip",
            checksum: "ae4bf34918f94251b0c5124e7fd65bc19949b35f1f0f2a51086dacef16e24e33"
        ),
        .binaryTarget(
            name: "SCFUtilities_Shared",
            url: "\(base)/WebexSDK-Shared-SCFUtilities.xcframework.zip",
            checksum: "155c9e2b03ebf30b790c219ed688f0013388e39984d60f469e787a6ec79e04f5"
        ),

        // ---------- Full ----------
        .binaryTarget(
            name: "WebexSDK_Full",
            url: "\(base)/WebexSDK-Full-WebexSDK.xcframework.zip",
            checksum: "77e4ff85ec422fae124c9f4413d222bd4e72bc34c521533f4bf934fc517e7a96"
        ),
        .binaryTarget(
            name: "UCFBridge_Full",
            url: "\(base)/WebexSDK-Full-UCFBridge.xcframework.zip",
            checksum: "1253ac8f763bc66594a91a9c09e0d4441db78229c6eb6049abd158e081ba0fd5"
        ),

        // ---------- Meeting ----------
        .binaryTarget(
            name: "WebexSDK_Meeting",
            url: "\(base)/WebexSDK-Meeting-WebexSDK.xcframework.zip",
            checksum: "42910061751c16da928118cdf44d6c4126fcd7dd04747390b997993a5d41d613"
        ),
        .binaryTarget(
            name: "UCFBridge_Meeting",
            url: "\(base)/WebexSDK-Meeting-UCFBridge.xcframework.zip",
            checksum: "a008d6d4e6c664884b68a2423239ec7e7180df87fd04b1ff4cd17402d493820c"
        ),

        // ---------- Wxc ----------
        .binaryTarget(
            name: "WebexSDK_Wxc",
            url: "\(base)/WebexSDK-Wxc-WebexSDK.xcframework.zip",
            checksum: "7254a4564c311a9d13f4c97cb4141626ca2f05e5d9fd02145d3f5edf9f3b3898"
        ),
        .binaryTarget(
            name: "UCFBridge_Wxc",
            url: "\(base)/WebexSDK-Wxc-UCFBridge.xcframework.zip",
            checksum: "52d9aeb2cafa9d0905b20c71b8218d46f5e5a6ab310c4d94d3c3bce8f5910411"
        ),

        // ---------- Message ----------
        .binaryTarget(
            name: "WebexSDK_Message",
            url: "\(base)/WebexSDK-Message-WebexSDK.xcframework.zip",
            checksum: "33dbc44b17433e8de95d063e151f004d60b150d2616c31858ebdb3d9b6d2a0b6"
        ),
        .binaryTarget(
            name: "UCFBridge_Message",
            url: "\(base)/WebexSDK-Message-UCFBridge.xcframework.zip",
            checksum: "4eabf375d2683f45f842d45867a0ccf4837b62a7537c0c8b5d075ede5b5dd70c"
        ),

        // ---------- Broadcast (standalone product, shipped once) ----------
        .binaryTarget(
            name: "WebexBroadcastExtensionKit",
            url: "\(base)/WebexBroadcastExtensionKit.xcframework.zip",
            checksum: "085a9bbc38276ece8d4600749de3c81b7dad3851480102da9679176006a8ae42"
        ),
    ]
)
